import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menulateral from "@/components/menuLateral/page";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-black ${inter.className}`}>
        <div className="flex flex-col md:flex-row">
          <div className="md:w-1/6 bg-[var(--corPrincipal)]">
            <Menulateral />
          </div>
          <div className="md:w-5/6">
            <div className="pt-4 pb-4 pl-4 pr-4">{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
